version: '3'
services:
  discord-music-bot:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    container_name: dc-docker
    command: npm start